language: c
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libjansson-dev libglib2.0-dev libzmq3-dev git build-essential libtool pkg-config autotools-dev autoconf automake cmake uuid-dev libpcre3-dev valgrind
    - git clone git://github.com/zeromq/czmq.git && cd czmq && ./autogen.sh && ./configure && sudo make install && sudo ldconfig && cd ..
script: make tests
notifications:
      email: false
